/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechHubIndexRouteImport } from './routes/tech-hub.index'
import { Route as TechHubSlugRouteImport } from './routes/tech-hub.$slug'
import { Route as TechHubMobileIndexRouteImport } from './routes/tech-hub.mobile.index'
import { Route as TechHubMobileSlugRouteImport } from './routes/tech-hub.mobile.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechHubIndexRoute = TechHubIndexRouteImport.update({
  id: '/tech-hub/',
  path: '/tech-hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechHubSlugRoute = TechHubSlugRouteImport.update({
  id: '/tech-hub/$slug',
  path: '/tech-hub/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TechHubMobileIndexRoute = TechHubMobileIndexRouteImport.update({
  id: '/tech-hub/mobile/',
  path: '/tech-hub/mobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechHubMobileSlugRoute = TechHubMobileSlugRouteImport.update({
  id: '/tech-hub/mobile/$slug',
  path: '/tech-hub/mobile/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/tech-hub/$slug': typeof TechHubSlugRoute
  '/tech-hub/': typeof TechHubIndexRoute
  '/tech-hub/mobile/$slug': typeof TechHubMobileSlugRoute
  '/tech-hub/mobile/': typeof TechHubMobileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/tech-hub/$slug': typeof TechHubSlugRoute
  '/tech-hub': typeof TechHubIndexRoute
  '/tech-hub/mobile/$slug': typeof TechHubMobileSlugRoute
  '/tech-hub/mobile': typeof TechHubMobileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/tech-hub/$slug': typeof TechHubSlugRoute
  '/tech-hub/': typeof TechHubIndexRoute
  '/tech-hub/mobile/$slug': typeof TechHubMobileSlugRoute
  '/tech-hub/mobile/': typeof TechHubMobileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/tech-hub/$slug'
    | '/tech-hub/'
    | '/tech-hub/mobile/$slug'
    | '/tech-hub/mobile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/tech-hub/$slug'
    | '/tech-hub'
    | '/tech-hub/mobile/$slug'
    | '/tech-hub/mobile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/tech-hub/$slug'
    | '/tech-hub/'
    | '/tech-hub/mobile/$slug'
    | '/tech-hub/mobile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  TechHubSlugRoute: typeof TechHubSlugRoute
  TechHubIndexRoute: typeof TechHubIndexRoute
  TechHubMobileSlugRoute: typeof TechHubMobileSlugRoute
  TechHubMobileIndexRoute: typeof TechHubMobileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-hub/': {
      id: '/tech-hub/'
      path: '/tech-hub'
      fullPath: '/tech-hub/'
      preLoaderRoute: typeof TechHubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-hub/$slug': {
      id: '/tech-hub/$slug'
      path: '/tech-hub/$slug'
      fullPath: '/tech-hub/$slug'
      preLoaderRoute: typeof TechHubSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-hub/mobile/': {
      id: '/tech-hub/mobile/'
      path: '/tech-hub/mobile'
      fullPath: '/tech-hub/mobile/'
      preLoaderRoute: typeof TechHubMobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-hub/mobile/$slug': {
      id: '/tech-hub/mobile/$slug'
      path: '/tech-hub/mobile/$slug'
      fullPath: '/tech-hub/mobile/$slug'
      preLoaderRoute: typeof TechHubMobileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  TechHubSlugRoute: TechHubSlugRoute,
  TechHubIndexRoute: TechHubIndexRoute,
  TechHubMobileSlugRoute: TechHubMobileSlugRoute,
  TechHubMobileIndexRoute: TechHubMobileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
